### ISSUE TITLE
Documentation fails to generate via NPM scrips on Windows

### ISSUE THREAD

**Issue by mikeomeara1** [mapbox/mapbox-sdk-js#293]
The `package.json` scrips `document-services`, `document-classes`, `document` and `precommit` fail to run on Windows due to the `documentation.js` errors:

```
Table of contents defined sorting of MapiRequest but no documentation with that namepath was found
Table of contents defined sorting of MapiResponse but no documentation with that namepath was found
Table of contents defined sorting of MapiError but no documentation with that namepath was found
Table of contents defined sorting of MapiClient but no documentation with that namepath was found
Table of contents defined sorting of Styles but no documentation with that namepath was found
Table of contents defined sorting of Static but no documentation with that namepath was found
....
Error: README.md
  115:31-115:100  warning  Link to unknown heading in `docs/classes.md`: `mapirequest`   missing-heading-in-file  remark-validate-links
  163:31-163:102  warning  Link to unknown heading in `docs/classes.md`: `mapiresponse`  missing-heading-in-file  remark-validate-links
   204:31-204:96  warning  Link to unknown heading in `docs/classes.md`: `mapierror`     missing-heading-in-file  remark-validate-links

‼ 3 warnings

    at Function.module.exports.sync (C:\Projects\@mapbox\mapbox-sdk-js\node_modules\remark-preset-davidtheclark\node_modules\execa\index.js:303:26)
    at Object.<anonymous> (C:\Projects\@mapbox\mapbox-sdk-js\node_modules\remark-preset-davidtheclark\bin.js:12:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
```

This also prevents a `git commit` due to the failing `precommit` script. I had to commit with `--no-verify` in order to proceed.

**Comment by davidtheclark** [comment]
Thanks for pointing this out, @mikeomeara1. I think we should be able to fix this by using `\"` (escaped double quotation marks) to wrap globs instead of `'` (single quotation marks). @danswick any interest in looking into this?

**Comment by mikeomeara1** [comment]
@davidtheclark @danswick I was able to confirm the suggested escape does indeed solve this issue on windows. After doing so, I was able to commit through vs-code normally.

The changes to `package.json` can be found [here](https://github.com/mikeomeara1/mapbox-sdk-js/blob/windows-docs-fix/package.json). I suppose we'd just need to confirm this didn't break anything on a non-windows platform.

If you'd like a PR...just let me know.
